/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bdaula01;

/**
 *
 * @author laboratorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadastroPessoa = new javax.swing.JMenuItem();
        menuCadastroVeiculo = new javax.swing.JMenuItem();
        menuEditaExcluiPessoa = new javax.swing.JMenuItem();
        menuEditaExcluiVeiculo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemRelatPesoas = new javax.swing.JMenuItem();
        MenuItemRelatVeiculos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        menuCadastroPessoa.setText("Cadastro de Pessoas");
        menuCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroPessoa);

        menuCadastroVeiculo.setText("Cadastro de Veiculos");
        menuCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroVeiculo);

        menuEditaExcluiPessoa.setText("Editar E Excluir Pessoas");
        menuEditaExcluiPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditaExcluiPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditaExcluiPessoa);

        menuEditaExcluiVeiculo.setText("Editar E Excluir Veiculos");
        menuEditaExcluiVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditaExcluiVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditaExcluiVeiculo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        MenuItemRelatPesoas.setText("Relatório Pessoas");
        MenuItemRelatPesoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRelatPesoasActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemRelatPesoas);

        MenuItemRelatVeiculos.setText("Relatório Veiculos");
        MenuItemRelatVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRelatVeiculosActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemRelatVeiculos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPessoaActionPerformed
        CadastraPessoaNoBanco cadPessoa = new CadastraPessoaNoBanco();
        cadPessoa.setVisible(true);
    }//GEN-LAST:event_menuCadastroPessoaActionPerformed

    private void menuEditaExcluiPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditaExcluiPessoaActionPerformed
        EditarExcluirPessoa editDeletePessoa = new EditarExcluirPessoa();
        editDeletePessoa.setVisible(true);
    }//GEN-LAST:event_menuEditaExcluiPessoaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void MenuItemRelatPesoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRelatPesoasActionPerformed
        RelatorioPessoas relataPessoas = new RelatorioPessoas();
        relataPessoas.setVisible(true);
    }//GEN-LAST:event_MenuItemRelatPesoasActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroVeiculoActionPerformed
        CadastraVeiculoNoBanco cadVeiculo = new CadastraVeiculoNoBanco();
        cadVeiculo.setVisible(true);
    }//GEN-LAST:event_menuCadastroVeiculoActionPerformed

    private void menuEditaExcluiVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditaExcluiVeiculoActionPerformed
        EditarExcluirVeiculo editDeleteVeiculo = new EditarExcluirVeiculo();
        editDeleteVeiculo.setVisible(true);
    }//GEN-LAST:event_menuEditaExcluiVeiculoActionPerformed

    private void MenuItemRelatVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRelatVeiculosActionPerformed
           RelatorioVeiculos relataVeiculos = new RelatorioVeiculos();
           relataVeiculos.setVisible(true);
    }//GEN-LAST:event_MenuItemRelatVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemRelatPesoas;
    private javax.swing.JMenuItem MenuItemRelatVeiculos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadastroPessoa;
    private javax.swing.JMenuItem menuCadastroVeiculo;
    private javax.swing.JMenuItem menuEditaExcluiPessoa;
    private javax.swing.JMenuItem menuEditaExcluiVeiculo;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
